server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    config:
      allow: true
    discovery:
      enabled: true
okta:
  oauth2:
    issuer: https://dev-kat1rgca2l8mbhi3.us.auth0.com/
    clientId: ${AUTH0_CLIENT_ID}
    clientSecret: ${AUTH0_CLIENT_SECRET}
    audience: https://dev-kat1rgca2l8mbhi3.us.auth0.com/api/v2/
    machineClientId: ${MACHINE_AUTH0_CLIENT_ID}
    machineClientSecret: ${MACHINE_AUTH0_CLIENT_SECRET}