server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/comment
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  cloud:
    config:
      allow: true
    discovery:
      enabled: true