server:
  port: 8888
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: experiences
          uri: http://localhost:8090/
          predicates:
            - Path=/api/experiences/**
        - id: comments
          uri: http://localhost:8091/
          predicates:
            - Path=/api/comments/**
okta:
  oauth2:
    issuer: https://dev-kat1rgca2l8mbhi3.us.auth0.com/
    clientId: ${AUTH0_CLIENT_ID}
    clientSecret: ${AUTH0_CLIENT_SECRET}
    audience: https://dev-kat1rgca2l8mbhi3.us.auth0.com/api/v2/