server:
  port: 8888
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: experience
          uri: http://localhost:8090/
          predicates:
            - Path=/api/experience/**